#!/usr/bin/env bash
# Bash script to display information about subdomains

if [ $# -eq 0 ]; then
    domain="asheo.tech"
    subdomains=("www" "lb-01" "web-01" "web-02")
elif [ $# -eq 1 ]; then
    domain=$1
    subdomains=("www" "lb-01" "web-01" "web-02")
elif [ $# -eq 2 ]; then
    domain=$1
    subdomains=($2)
fi

for subdomain in "${subdomains[@]}"; do
    record_type=$(dig $subdomain.$domain | awk '/ANSWER SECTION/ {getline; print $4}')
    destination=$(dig $subdomain.$domain | awk '/ANSWERSECTION/ {getline; print $5}')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
done
