#!/usr/bin/env bash
# Install nginx on your web-01 server

sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

sudo rm -f /var/www/html/index.html

sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'

sudo service nginx restart
