#!/usr/bin/env bash
# Install nginx on your web-01 server

apt-get update
apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

echo "server {
    listen 80;
    location / {
        echo 'Hello World!';
    }
}" > /etc/nginx/sites-available/default

service nginx restart
