#!/usr/bin/env bash
# This script configures an Ubuntu machine to meet the task requirements

sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'

sudo service nginx restart
