#!/usr/bin/env bash
# setting up a 404 error page

if ! command -v nginx >/dev/null 2>&1; then
    sudo apt-get update
    sudo apt-get install -y nginx
fi

sudo sh -c 'echo "Ceci n\'est pas une page" > /var/www/html/404.html'

sudo sh -c 'echo "error_page 404 /404.html;
location = /404.html {
    internal;
}" > /etc/nginx/sites-available/custom-error'

sudo ln -sf /etc/nginx/sites-available/custom-error /etc/nginx/sites-enabled/
sudo rm -f /etc/nginx/sites-enabled/default
sudo service nginx restart
