#!/usr/bin/env bash
# This script configures Nginx to add a custom response header

apt-get update
apt-get install -y nginx

sudo vim -c "normal G" -c "normal o \ \ add_header X-Served-By \$hostname;" -c "wq" /etc/nginx/nginx.conf

service nginx restart
