#!/usr/bin/env bash
# This script configures Nginx to add a custom response header

apt-get update
apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

sudo sed -i 's/# server_tokens off;/server_tokens off;\n        add_header X-Served-By $hostname;/g' /etc/nginx/nginx.conif

service nginx restart
