#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get update
sudo apt-get install -y haproxy

sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

sudo tee /etc/haproxy/haproxy.cfg > /dev/null << EOF
frontend lb-frontend
    bind *:80
    mode http
    default_backend lb-backend

backend lb-backend
    mode http
    balance roundrobin
    option forwardfor
    server 206861-web-01 34.224.2.128 check
    server 206861-web-02 100.24.206.245 check
EOF

sudo systemctl restart haproxy
