#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get update
sudo apt-get install -y haproxy

printf %s "
frontend proxynode
    bind *:80
    mode http
    default_backend web-backend

backend web-backend
    balance roundrobin
    option forwardfor
    server 206861-web-01 34.224.2.128 check
    server 206861-web-02 100.24.206.245 check
" >> /etc/haproxy/haproxy.cfg

sudo systemctl restart haproxy
