#!/usr/bin/env bash
# Configure Nginx to listen on port 80

sudo ufw allow 'Nginx HTTP'
sudo sed -i 's/default_server;/default_server; listen 80;/g' /etc/nginx/sites-available/default
sudo service nginx restart
