#!/usr/bin/env bash
# Bash script that configures a server listening to port 80

apt-get update
apt-get install -y net-tools

systemctl status nginx

netstat -tuln | grep ":80"

nginx -t

systemctl restart nginx
