#!/usr/bin/env bash
# Bash script run the whoami under the user passed
if [ -z "$1" ]; then
    echo "Usage: $0 <username>"
    exit 1
fi

user_home=$(getent passwd "$1" | cut -d: -f6)

su - "$1" -c 'HOME='"$user_home"' whoami'
