#!/usr/bin/env bash
# Using what you did for task #1, make your fix short and sweet
sed -i 's/user  nginx;/user  nginx;\n/g' /etc/nginx/nginx.conf
sed -i 's/# server_names_hash_bucket_size/server_names_hash_bucket_size/g' /etc/nginx/nginx.conf
sed -i 's/listen       80;/listen       8080;/g' /etc/nginx/sites-available/default
nginx -g "daemon off;"
echo "Nginx configuration has been updated."
